@echo off
REM rclean.bat
REM   Prepare test directories for distribution.
REM
REM   1)  reloc Test Directories
cd as1802
call ..\..\..\_xfiles.bat
cd ..
cd as2650
call ..\..\..\_xfiles.bat
cd ..
cd as4040
call ..\..\..\_xfiles.bat
cd ..
cd as430
call ..\..\..\_xfiles.bat
cd ..
cd as6100
call ..\..\..\_xfiles.bat
cd ..
cd as61860
call ..\..\..\_xfiles.bat
cd ..
cd as6500
call ..\..\..\_xfiles.bat
cd ..
cd as6800
call ..\..\..\_xfiles.bat
cd ..
cd as6801
call ..\..\..\_xfiles.bat
cd ..
cd as6804
call ..\..\..\_xfiles.bat
cd ..
cd as6805
call ..\..\..\_xfiles.bat
cd ..
cd as6808
call ..\..\..\_xfiles.bat
cd ..
cd as6809
call ..\..\..\_xfiles.bat
cd ..
cd as6811
call ..\..\..\_xfiles.bat
cd ..
cd as6812
call ..\..\..\_xfiles.bat
cd ..
cd as6816
call ..\..\..\_xfiles.bat
cd ..
cd as68cf
call ..\..\..\_xfiles.bat
cd ..
cd as68k
call ..\..\..\_xfiles.bat
cd ..
cd as740
call ..\..\..\_xfiles.bat
cd ..
cd as78k0
call ..\..\..\_xfiles.bat
cd ..
cd as78k0s
call ..\..\..\_xfiles.bat
cd ..
cd as8008
call ..\..\..\_xfiles.bat
cd ..
cd as8008s
call ..\..\..\_xfiles.bat
cd ..
cd as8048
call ..\..\..\_xfiles.bat
cd ..
cd as8051
call ..\..\..\_xfiles.bat
cd ..
cd as8085
call ..\..\..\_xfiles.bat
cd ..
cd as89lp
call ..\..\..\_xfiles.bat
cd ..
cd as8xcxxx
call ..\..\..\_xfiles.bat
cd ..
cd asavr
call ..\..\..\_xfiles.bat
cd ..
cd ascop4
call ..\..\..\_xfiles.bat
cd ..
cd ascop8
call ..\..\..\_xfiles.bat
cd ..
cd asez8
call ..\..\..\_xfiles.bat
cd ..
cd asez80
call ..\..\..\_xfiles.bat
cd ..
cd asf2mc8
call ..\..\..\_xfiles.bat
cd ..
cd asf8
call ..\..\..\_xfiles.bat
cd ..
cd asgb
call ..\..\..\_xfiles.bat
cd ..
cd ash8
call ..\..\..\_xfiles.bat
cd ..
cd asm8c
call ..\..\..\_xfiles.bat
cd ..
cd aspdp11
call ..\..\..\_xfiles.bat
cd ..
cd aspic
call ..\..\..\_xfiles.bat
cd ..
cd asrab
call ..\..\..\_xfiles.bat
cd ..
cd asrs08
call ..\..\..\_xfiles.bat
cd ..
cd asscmp
call ..\..\..\_xfiles.bat
cd ..
cd asst6
call ..\..\..\_xfiles.bat
cd ..
cd asst7
call ..\..\..\_xfiles.bat
cd ..
cd asst8
call ..\..\..\_xfiles.bat
cd ..
cd assx
call ..\..\..\_xfiles.bat
cd ..
cd astlcs90
call ..\..\..\_xfiles.bat
cd ..
cd asz280
call ..\..\..\_xfiles.bat
cd ..
cd asz8
call ..\..\..\_xfiles.bat
cd ..
cd asz80
call ..\..\..\_xfiles.bat
cd ..
cd reloc
call ..\..\..\_xfiles.bat
cd ..
